# Generated by Django 2.2 on 2020-08-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('department', models.CharField(max_length=64, unique=True, verbose_name='单位')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='单位代码')),
                ('category', models.CharField(max_length=12, verbose_name='类别')),
                ('flag', models.CharField(default='False', max_length=12)),
            ],
            options={
                'verbose_name': '单位表',
                'verbose_name_plural': '单位表',
                'db_table': '单位表',
            },
        ),
    ]
