# Generated by Django 2.2 on 2020-08-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bumen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='flag',
        ),
    ]
