# Generated by Django 2.2 on 2020-08-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('position', models.CharField(max_length=12, unique=True, verbose_name='职位')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='职位代码')),
            ],
            options={
                'verbose_name': '职位表',
                'verbose_name_plural': '职位表',
                'db_table': '职位表',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('rank', models.CharField(max_length=12, unique=True, verbose_name='职级')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='职级代码')),
            ],
            options={
                'verbose_name': '职级表',
                'verbose_name_plural': '职级表',
                'db_table': '职级表',
            },
        ),
    ]
