# Generated by Django 2.2 on 2020-08-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zhiwei', '0001_initial'),
        ('Bumen', '0001_initial'),
        ('Renyuan', '0001_initial'),
        ('Fangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jggbTongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index1', models.SmallIntegerField(verbose_name='指标1')),
                ('index2', models.SmallIntegerField(verbose_name='指标2')),
                ('index3', models.SmallIntegerField(verbose_name='指标3')),
                ('index4', models.SmallIntegerField(verbose_name='指标4')),
                ('index5', models.SmallIntegerField(verbose_name='指标5')),
                ('index6', models.SmallIntegerField(verbose_name='指标6')),
                ('index7', models.SmallIntegerField(verbose_name='指标7')),
                ('index8', models.SmallIntegerField(verbose_name='指标8')),
                ('index9', models.SmallIntegerField(verbose_name='指标9')),
                ('index10', models.SmallIntegerField(verbose_name='指标10')),
                ('index11', models.SmallIntegerField(verbose_name='指标11')),
                ('index12', models.SmallIntegerField(verbose_name='指标12')),
                ('index13', models.SmallIntegerField(verbose_name='指标13')),
                ('index14', models.SmallIntegerField(verbose_name='指标14')),
                ('index15', models.SmallIntegerField(verbose_name='指标15')),
                ('index16', models.SmallIntegerField(verbose_name='指标16')),
                ('index17', models.SmallIntegerField(verbose_name='指标17')),
                ('index18', models.SmallIntegerField(verbose_name='指标18')),
                ('giveup', models.BooleanField(default=False, verbose_name='放弃测评')),
                ('beiceping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jggbbeiceping', to='Renyuan.Beiceping', to_field='IDcard', verbose_name='被测评人')),
                ('ceping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jggbceping', to='Renyuan.Ceping', to_field='IDcard', verbose_name='测评人')),
                ('depNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jggbdanweidaima', to='Bumen.Department', to_field='number', verbose_name='单位代码')),
                ('rankNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jggbzhijidaima', to='Zhiwei.Rank', to_field='number', verbose_name='职级代码')),
            ],
            options={
                'verbose_name': '机关干部统计表',
                'verbose_name_plural': '机关干部统计表',
                'db_table': '机关干部统计表',
            },
        ),
        migrations.CreateModel(
            name='jggbResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index1', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标1')),
                ('index2', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标2')),
                ('index3', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标3')),
                ('index4', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标4')),
                ('index5', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标5')),
                ('index6', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标6')),
                ('index7', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标7')),
                ('index8', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标8')),
                ('index9', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标9')),
                ('index10', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标10')),
                ('index11', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标11')),
                ('index12', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标12')),
                ('index13', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标13')),
                ('index14', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标14')),
                ('index15', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标15')),
                ('index16', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标16')),
                ('index17', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标17')),
                ('index18', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='指标18')),
                ('level', models.CharField(max_length=12, verbose_name='级别')),
                ('zhiwu', models.CharField(max_length=12, verbose_name='职务')),
                ('count', models.CharField(max_length=5, verbose_name='测评人数')),
                ('index19', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标19')),
                ('index20', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标20')),
                ('index21', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标21')),
                ('index22', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标22')),
                ('index23', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标23')),
                ('score', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='测评分数')),
                ('beiceping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_jggbbeiceping', to='Renyuan.Beiceping', to_field='IDcard', verbose_name='被测评人')),
                ('depNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jggbdanwei', to='Bumen.Department', to_field='number', verbose_name='单位')),
            ],
            options={
                'verbose_name': '机关干部结果表',
                'verbose_name_plural': '机关干部结果表',
                'db_table': '机关干部结果表',
            },
        ),
    ]
