# Generated by Django 2.2 on 2020-08-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0002_jggbresult_jggbtongji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jggbresult',
            name='index1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标1'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标10'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标11'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标12'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index13',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标13'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标14'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index15',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标15'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标16'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index17',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标17'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index18',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标18'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标2'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标3'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标4'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标5'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标6'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标7'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标8'),
        ),
        migrations.AlterField(
            model_name='jggbresult',
            name='index9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标9'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标1'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index10',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标10'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index11',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标11'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index12',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标12'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index13',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标13'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index14',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标14'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index15',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标15'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index16',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标16'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index17',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标17'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index18',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标18'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标2'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标3'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标4'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标5'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index6',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标6'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index7',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标7'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index8',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标8'),
        ),
        migrations.AlterField(
            model_name='jggbtongji',
            name='index9',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标9'),
        ),
    ]
