# Generated by Django 2.2 on 2020-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0003_auto_20200802_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jggbindexweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='jggbindexweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='权重'),
        ),
    ]
