# Generated by Django 2.2 on 2020-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0004_auto_20200802_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbcpweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='gbcpweight',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='gbcpweight',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='jggbindexweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
    ]
