# Generated by Django 2.2 on 2020-08-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0005_auto_20200802_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzcpweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AddField(
            model_name='xybzindexweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AddField(
            model_name='xygbindexweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AddField(
            model_name='zsdwbzindexweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AddField(
            model_name='zsdwgbindexweight',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='bzcpweight',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='bzcpweight',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='gbcpweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='xybzindexweight',
            name='index',
            field=models.CharField(max_length=12, null=True, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='xybzindexweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='xygbindexweight',
            name='index',
            field=models.CharField(max_length=12, null=True, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='xygbindexweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='zsdwbzindexweight',
            name='index',
            field=models.CharField(max_length=12, null=True, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='zsdwbzindexweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='zsdwgbindexweight',
            name='index',
            field=models.CharField(max_length=12, null=True, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='zsdwgbindexweight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='权重'),
        ),
    ]
