# Generated by Django 2.2 on 2020-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0006_auto_20200804_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xybztongji',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='fzsl',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='fzts',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='kxjc',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='mbgl',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='mzgl',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='nhjs',
        ),
        migrations.RemoveField(
            model_name='xybztongji',
            name='tsld',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='bsxl',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='ddpx',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='gfgl',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='gzsl',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='gzzf',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='jltr',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='ljzl',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='mbwc',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='tcyj',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='zznl',
        ),
        migrations.RemoveField(
            model_name='xygbtongji',
            name='zzpz',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='fwbz',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='fzsl',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='fzts',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='kxjc',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='mbwc',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='yxjz',
        ),
        migrations.RemoveField(
            model_name='zsdwbztongji',
            name='zhxy',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='bsxl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='ddpx',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='gfgl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='ggzf',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='gzsl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='jyjs',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='ljzl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='mbwc',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='tcyj',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='zznl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbtongji',
            name='zzpz',
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index10',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index11',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index12',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index6',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index7',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index8',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='xybztongji',
            name='index9',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标9'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index10',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index11',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index12',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index13',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标13'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index14',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标14'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index15',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标15'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index16',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标16'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index17',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标17'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index18',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标18'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index6',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index7',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index8',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='xygbtongji',
            name='index9',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标9'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index10',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index11',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index12',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index6',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index7',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index8',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='zsdwbztongji',
            name='index9',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标9'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index10',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index11',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index12',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index13',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标13'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index14',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标14'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index15',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标15'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index16',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标16'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index17',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标17'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index18',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标18'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index6',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index7',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index8',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='zsdwgbtongji',
            name='index9',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='指标9'),
        ),
        migrations.AlterField(
            model_name='bzcpweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='xybzindexweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='xygbindexweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='zsdwbzindexweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
        migrations.AlterField(
            model_name='zsdwgbindexweight',
            name='code',
            field=models.CharField(max_length=12, verbose_name='指标代码'),
        ),
    ]
