# Generated by Django 2.2 on 2020-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0007_auto_20200804_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xybzresult',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='fzsl',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='fzts',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='kxjc',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='mbgl',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='mzgl',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='nhjs',
        ),
        migrations.RemoveField(
            model_name='xybzresult',
            name='tsld',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='bsxl',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='bzcy',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='ddpx',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='dkjg',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='gfgl',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='gzsl',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='gzzf',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='jltr',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='ljzl',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='mbwc',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='tcyj',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='xy_xld',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='xyss',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='zznl',
        ),
        migrations.RemoveField(
            model_name='xygbresult',
            name='zzpz',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='dwzgssdb',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='dzfzr',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='fwbz',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='fzsl',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='fzts',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='kxjc',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='mbwc',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='xld',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='yxjz',
        ),
        migrations.RemoveField(
            model_name='zsdwbzresult',
            name='zhxy',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='bsxl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='cxys',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='ddpx',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='dwbz',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='gfgl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='ggzf',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='gzsl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='jyjs',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='ljzl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='mbwc',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='tcyj',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='xgry',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='zsdw_xld',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='zsdw_xyld',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='zsdw_xyxg',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='zznl',
        ),
        migrations.RemoveField(
            model_name='zsdwgbresult',
            name='zzpz',
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='xybzresult',
            name='index9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标9'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index13',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标13'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标14'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index15',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标15'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标16'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index17',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标17'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index18',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标18'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index19',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标19'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标20'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index21',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标21'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index22',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标22'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='xygbresult',
            name='index9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标9'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index19',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标19'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标20'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index21',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标21'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='zsdwbzresult',
            name='index9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标9'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标1'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标10'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标11'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标12'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index13',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标13'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index14',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标14'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index15',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标15'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index16',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标16'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index17',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标17'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index18',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标18'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index19',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标19'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标2'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标20'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index21',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标21'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index22',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标22'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index23',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标23'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标3'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标4'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标5'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标6'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标7'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标8'),
        ),
        migrations.AddField(
            model_name='zsdwgbresult',
            name='index9',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指标9'),
        ),
    ]
