# Generated by Django 2.2 on 2020-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0008_auto_20200805_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('code', models.CharField(max_length=12, verbose_name='代码')),
            ],
            options={
                'verbose_name': '属性表',
                'verbose_name_plural': '属性表',
                'db_table': '属性表',
            },
        ),
        migrations.CreateModel(
            name='BanziLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='被考核班子')),
                ('code', models.CharField(max_length=12, verbose_name='代码')),
                ('category', models.CharField(max_length=12, verbose_name='分类')),
            ],
            options={
                'verbose_name': '被考核班子身份表',
                'verbose_name_plural': '被考核班子身份表',
                'db_table': '被考核班子身份表',
            },
        ),
        migrations.CreateModel(
            name='CepingLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='参评身份')),
                ('code', models.CharField(max_length=12, verbose_name='代码')),
                ('category', models.CharField(max_length=12, verbose_name='分类')),
            ],
            options={
                'verbose_name': '参评身份',
                'verbose_name_plural': '参评身份',
                'db_table': '参评身份',
            },
        ),
        migrations.CreateModel(
            name='GanbuLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='被考核干部')),
                ('code', models.CharField(max_length=12, verbose_name='代码')),
                ('category', models.CharField(max_length=12, verbose_name='分类')),
            ],
            options={
                'verbose_name': '被考核干部身份表',
                'verbose_name_plural': '被考核干部身份表',
                'db_table': '被考核干部身份表',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceping_code', models.CharField(max_length=12, verbose_name='参评代码')),
                ('ganbu_code', models.TextField(verbose_name='被考核干部代码')),
                ('banzi_code', models.TextField(verbose_name='被考核班子代码')),
            ],
            options={
                'verbose_name': '考核关系对应表',
                'verbose_name_plural': '考核关系对应表',
                'db_table': '考核关系对应表',
            },
        ),
        migrations.AddField(
            model_name='bztjinfo',
            name='label',
            field=models.TextField(default='', verbose_name='班子标签'),
        ),
    ]
