# Generated by Django 2.2 on 2020-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0009_auto_20200808_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banzilabel',
            name='code',
            field=models.CharField(max_length=12, unique=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='cepinglabel',
            name='code',
            field=models.CharField(max_length=12, unique=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='ganbulabel',
            name='code',
            field=models.CharField(max_length=12, unique=True, verbose_name='代码'),
        ),
    ]
