# Generated by Django 2.2 on 2020-09-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0011_remove_beiceping_attribute'),
        ('Fangan', '0010_auto_20200818_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
