# Generated by Django 2.2 on 2020-09-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0011_delete_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanziLabel',
        ),
        migrations.DeleteModel(
            name='CepingLabel',
        ),
        migrations.DeleteModel(
            name='GanbuLabel',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.RemoveField(
            model_name='bztjinfo',
            name='evaluation_index',
        ),
        migrations.RemoveField(
            model_name='bztjinfo',
            name='label',
        ),
    ]
