# Generated by Django 2.2 on 2020-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0012_auto_20200911_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bztjinfo',
            name='cePing',
            field=models.BooleanField(default=True, verbose_name='测评'),
        ),
    ]
