# Generated by Django 2.2 on 2020-08-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fangan', '0009_auto_20200808_1845'),
        ('Renyuan', '0003_auto_20200802_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='beiceping',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ceping_attrubute', to='Fangan.Attribute', verbose_name='单位属性'),
        ),
        migrations.AddField(
            model_name='beiceping',
            name='label',
            field=models.TextField(default='', verbose_name='干部标签'),
        ),
        migrations.AddField(
            model_name='ceping',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='测评身份标签'),
        ),
        migrations.AlterField(
            model_name='ceping',
            name='banZi_finished',
            field=models.TextField(verbose_name='领导班子已测评'),
        ),
        migrations.AlterField(
            model_name='ceping',
            name='banZi_unfinished',
            field=models.TextField(verbose_name='领导班子未测评'),
        ),
        migrations.AlterField(
            model_name='ceping',
            name='ganBu_finished',
            field=models.TextField(verbose_name='干部已测评'),
        ),
        migrations.AlterField(
            model_name='ceping',
            name='ganBu_unfinished',
            field=models.TextField(verbose_name='干部未测评'),
        ),
    ]
