# Generated by Django 2.2 on 2020-08-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0004_auto_20200808_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceping',
            name='session',
            field=models.CharField(max_length=32, null=True, verbose_name='当前是否已登录'),
        ),
    ]
