# Generated by Django 2.2 on 2020-08-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0005_ceping_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceping',
            old_name='session',
            new_name='sessionid',
        ),
    ]
