# Generated by Django 2.2 on 2020-09-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0007_specialstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiceping',
            name='EvaluationIndex',
        ),
    ]
