# Generated by Django 2.2 on 2020-09-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0008_remove_beiceping_evaluationindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiceping',
            name='label',
        ),
    ]
