# Generated by Django 2.2 on 2020-09-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0009_remove_beiceping_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiceping',
            name='attribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceping_attrubute', to='Fangan.Attribute', verbose_name='单位属性'),
        ),
    ]
