# Generated by Django 2.2 on 2020-09-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0010_auto_20200903_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiceping',
            name='attribute',
        ),
    ]
