# Generated by Django 2.2 on 2020-09-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0011_remove_beiceping_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceping',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ceping',
            name='education',
        ),
        migrations.RemoveField(
            model_name='ceping',
            name='job',
        ),
        migrations.RemoveField(
            model_name='ceping',
            name='label',
        ),
        migrations.RemoveField(
            model_name='ceping',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='ceping',
            name='political_status',
        ),
    ]
