# Generated by Django 2.2 on 2020-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renyuan', '0013_auto_20200908_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiceping',
            name='kaoHeZhe',
        ),
        migrations.AlterField(
            model_name='beiceping',
            name='cePing',
            field=models.BooleanField(default=True, verbose_name='是否参与测评'),
        ),
    ]
