# Generated by Django 2.2 on 2020-08-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bumen', '0001_initial'),
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bumen.Department', to_field='number', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否为超级管理员'),
        ),
    ]
