# Generated by Django 2.2 on 2020-08-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20200806_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super',
        ),
    ]
